	IMPLICIT REAL*8(A-H,O-Z)
	PARAMETER (NN=200)
	DIMENSION AKI(NN),CKI(NN)
	DELTA=0.2D0
	PI=4.0D0*DATAN(1.0D0)
	AK0=20.0D0
	AKMIN=-80.0D0
	AKMAX=80.0D0
	DK=(AKMAX-AKMIN)/DFLOAT(NN)
	SUM=0.0D0
	DO I=1,NN
	  AKI(I)=AKMIN+(I-1)*DK
	  CKI(I)=DSQRT(2.0D0/PI)*DELTA
     1	        *EXP(-2.0D0*DELTA*DELTA*(AKI(I)-AK0)**2)
	  SUM=SUM+CKI(I)*DK
	  WRITE(6,'(1X,I8,2F12.6)')I,AKI(I),CKI(I)
	ENDDO
	WRITE(7,'(1X,F12.6)')SUM
	STOP
	END
CCCCCCC
      SUBROUTINE DEFAT(DT,AT)
      IMPLICIT REAL*8 (A-H,O-Z)
      PARAMETER (NSTP=4096)
      DIMENSION AT(NSTP)
      PI=4.0D0*DATAN(1.0D0)
      PI2=PI*2.0D0
      ACONST=PI2/(NSTP*DT)
      NHALFT = NSTP/2+1
      DO I=1,NHALFT
        AT(I)=ACONST*(I-1)
      ENDDO
      DO I=NHALFT+1,NSTP
        AT(I)=ACONST*(I-1-NSTP)
      ENDDO
      RETURN
      END

