      IMPLICIT REAL*8 (A-H,O-Z)
      COMPLEX*16 PS
      PARAMETER (N_R=512)
      PARAMETER (NSTEP=2100)
      PARAMETER (NSTP=2048)
      PARAMETER (NE=92)
      PARAMETER (LANMIN=14)
      PARAMETER (LANMAX=100)
      DIMENSION AKR(N_R)
      DIMENSION R(N_R)
      DIMENSION V0(N_R)
      DIMENSION PSIRE(N_R),PSIIM(N_R)
      DIMENSION PSRE(N_R),PSIM(N_R)
      DIMENSION X1(N_R),Y1(N_R)
      DIMENSION PS(N_R)
      DIMENSION AT(NSTP)
      DIMENSION CKI(NE),ET(NE)
      DIMENSION AKI(NE)
      DIMENSION NN(1)
      DIMENSION URT(N_R+1:2*N_R)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     FOR FFTW ROUTINES                                     C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      INTEGER*8 PLAN1,PLAN2
      DOUBLE COMPLEX ARR1,ARR
      DIMENSION ARR1(N_R)
      DIMENSION ARR(N_R)
      INTEGER FFTW_R2HC
      PARAMETER (FFTW_R2HC=0)
      INTEGER FFTW_HC2R
      PARAMETER (FFTW_HC2R=1)
      INTEGER FFTW_DHT
      PARAMETER (FFTW_DHT=2)
      INTEGER FFTW_REDFT00
      PARAMETER (FFTW_REDFT00=3)
      INTEGER FFTW_REDFT01
      PARAMETER (FFTW_REDFT01=4)
      INTEGER FFTW_REDFT10
      PARAMETER (FFTW_REDFT10=5)
      INTEGER FFTW_REDFT11
      PARAMETER (FFTW_REDFT11=6)
      INTEGER FFTW_RODFT00
      PARAMETER (FFTW_RODFT00=7)
      INTEGER FFTW_RODFT01
      PARAMETER (FFTW_RODFT01=8)
      INTEGER FFTW_RODFT10
      PARAMETER (FFTW_RODFT10=9)
      INTEGER FFTW_RODFT11
      PARAMETER (FFTW_RODFT11=10)
      INTEGER FFTW_FORWARD
      PARAMETER (FFTW_FORWARD=-1)
      INTEGER FFTW_BACKWARD
      PARAMETER (FFTW_BACKWARD=+1)
      INTEGER FFTW_MEASURE
      PARAMETER (FFTW_MEASURE=0)
      INTEGER FFTW_DESTROY_INPUT
      PARAMETER (FFTW_DESTROY_INPUT=1)
      INTEGER FFTW_UNALIGNED
      PARAMETER (FFTW_UNALIGNED=2)
      INTEGER FFTW_CONSERVE_MEMORY
      PARAMETER (FFTW_CONSERVE_MEMORY=4)
      INTEGER FFTW_EXHAUSTIVE
      PARAMETER (FFTW_EXHAUSTIVE=8)
      INTEGER FFTW_PRESERVE_INPUT
      PARAMETER (FFTW_PRESERVE_INPUT=16)
      INTEGER FFTW_PATIENT
      PARAMETER (FFTW_PATIENT=32)
      INTEGER FFTW_ESTIMATE
      PARAMETER (FFTW_ESTIMATE=64)
      INTEGER FFTW_TIMELIMIT
      PARAMETER (FFTW_TIMELIMIT=1073741824)
      INTEGER FFTW_ESTIMATE_PATIENT
      PARAMETER (FFTW_ESTIMATE_PATIENT=128)
      INTEGER FFTW_BELIEVE_PCOST
      PARAMETER (FFTW_BELIEVE_PCOST=256)
      INTEGER FFTW_NO_DFT_R2HC
      PARAMETER (FFTW_NO_DFT_R2HC=512)
      INTEGER FFTW_NO_NONTHREADED
      PARAMETER (FFTW_NO_NONTHREADED=1024)
      INTEGER FFTW_NO_BUFFERING
      PARAMETER (FFTW_NO_BUFFERING=2048)
      INTEGER FFTW_NO_INDIRECT_OP
      PARAMETER (FFTW_NO_INDIRECT_OP=4096)
      INTEGER FFTW_ALLOW_LARGE_GENERIC
      PARAMETER (FFTW_ALLOW_LARGE_GENERIC=8192)
      INTEGER FFTW_NO_RANK_SPLITS
      PARAMETER (FFTW_NO_RANK_SPLITS=16384)
      INTEGER FFTW_NO_VRANK_SPLITS
      PARAMETER (FFTW_NO_VRANK_SPLITS=32768)
      INTEGER FFTW_NO_VRECURSE
      PARAMETER (FFTW_NO_VRECURSE=65536)
      INTEGER FFTW_NO_SIMD
      PARAMETER (FFTW_NO_SIMD=131072)
      INTEGER FFTW_NO_SLOW
      PARAMETER (FFTW_NO_SLOW=262144)
      INTEGER FFTW_NO_FIXED_RADIX_LARGE_N
      PARAMETER (FFTW_NO_FIXED_RADIX_LARGE_N=524288)
      INTEGER FFTW_ALLOW_PRUNING
      PARAMETER (FFTW_ALLOW_PRUNING=1048576)
CCCCCC
      INA=1
      EVEPS=0.9648533822D0
      PI=4.0D0*DATAN(1.0D0)
      HBAR=0.06350781278D0
      RMIN=-50.0D0
      RMAX=50.0D0
      AM=1.0D0
      DR=(RMAX-RMIN)/DFLOAT(N_R)
      VOLEM=DR
      RMST=HBAR*HBAR/AM
      RINV=1.0D0/HBAR
      SN_G=1.0D0/DSQRT(DFLOAT(N_R))
      LAITER=30
      NLAN=LAITER
      EPSL1=1.0D-08
      EPSL2=1.0D-07
      NLDEL=2
      A1=1.0D0
      A2=2.0D0
      AK0=20.0D0
      EKIN=HBAR*HBAR*AK0*AK0/2.0D0/AM
CCC
      CALL DEFAK(DR,AKR)
      CALL TRANSF1(PSIRE,PSIIM)
      DO I=1,N_R
        R(I)=RMIN+(I-1)*DR
      ENDDO
      DO I=1,N_R
        RH=R(I)
        CALL POTF(RH,EN)
        V0(I)=EN
        WRITE(7,'(2F12.6)')RH,EN
      ENDDO
CCCCCC
      AKMIN=15.0D0
      AKMAX=24.0D0
      DO I=1,10
      AAK=AKMIN+(I-1)*1.0D0
      FAC1=2.0D0*PI*AAK/A2
      FAC2=PI*DSQRT(8.0D0*AM*A1/A2/A2/HBAR/HBAR-1.0D0)
      PTRANS=(DCOSH(FAC1)-1.0D0)/(DCOSH(FAC1)+DCOSH(FAC2))
      WRITE(110,*)AAK,PTRANS
      ENDDO
      IDX=10
      T=0.0D0
      ISTEP=0
      DDT=0.01D0
      CALL INITIAL_WEIGHT(DDT,EKIN,IDX,AM,AT,ET,CKI)
      IF(INA.EQ.1)GOTO 100
      DO I=1,N_R
      PS(I)=DCMPLX(PSIRE(I),PSIIM(I))
      WRITE(30,'(1X,I8,4F12.6)')ISTEP,R(I),ABS(PS(I))
      ENDDO
      CALL DFFTW_PLAN_DFT_1D(PLAN1,N_R,ARR1,ARR1,
     &                       FFTW_FORWARD,FFTW_MEASURE)
      CALL DFFTW_PLAN_DFT_1D(PLAN2,N_R,ARR,ARR,
     &                       FFTW_BACKWARD,FFTW_MEASURE)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                          C
C         Time Propagation by Lanczos iteration            C
C                                                          C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
  50  ISTEP=ISTEP+1
      T=T+DDT
      DO I=1,N_R
        X1(I)=PSIRE(I)
        Y1(I)=PSIIM(I)
      ENDDO
      CALL ENERGY(X1,Y1,AKR,RMST,SN_G,V0,
     1VAL1,VAL2,VAL,VOLEM,PLAN1,PLAN2)
        EER1=VAL1*VOLEM/EVEPS
        EER2=VAL2*VOLEM/EVEPS
        EER=VAL*VOLEM/EVEPS
        MMM=NLAN
      CALL LANCZ(X1,Y1,DDT,VOLEM,RAV,MMM,ISTEP,AKR,
     2RMST,RINV,SN_G,V0,PLAN1,PLAN2)
      RAV=RAV*VOLEM
      IF (EPSL1.GT.0.0D0) THEN
        IF(RAV.LT.EPSL1) NLAN=NLAN-NLDEL
        IF(RAV.GT.EPSL2) NLAN=NLAN+NLDEL
        IF(NLAN.GT.LANMAX) NLAN=LANMAX
        IF(NLAN.LT.LANMIN) NLAN=LANMIN
      ENDIF
      WRITE(14,*)ISTEP,RAV,NLAN
      DO I=1,N_R
        PSRE(I)=X1(I)
        PSIM(I)=Y1(I)
      ENDDO
      WRITE(22,'(1X,4F12.6)')T,EER1,EER2,EER
      DO I=1,N_R
        PSIRE(I)=PSRE(I)
        PSIIM(I)=PSIM(I)
      ENDDO
      SS=0.0D0
      DO I=1,N_R
        SS=SS+(PSRE(I)**2+PSIM(I)**2)*VOLEM
      ENDDO
      WRITE(21,'(1X,4F12.6)')T,SS,EER/SS
      IF(MOD(ISTEP,100).EQ.0)THEN
      DO I=1,N_R
      PS(I)=DCMPLX(PSRE(I),PSIM(I))
      WRITE(30+ISTEP/100,'(1X,5F12.6)')T,R(I),ABS(PS(I))
      ENDDO
      ENDIF
CCCCCC
      IF(ISTEP.EQ.2000)THEN
      DO I=N_R/2+1,N_R
      URT(2*I-1)=PSRE(I)
      URT(2*I)=PSIM(I)
      WRITE(60,'(1X,3F12.6)')R(I),URT(2*I-1),URT(2*I)
      ENDDO
      ENDIF
CCCCCC
      IF (ISTEP.EQ.NSTEP) GO TO 40
      GO TO 50
  40  CONTINUE
      CALL DFFTW_DESTROY_PLAN(PLAN1)
      CALL DFFTW_DESTROY_PLAN(PLAN2)
  100 CONTINUE
      IF(INA.EQ.1)THEN
      DO I=1,N_R
      READ(60,'(1X,3F12.6)')R(I),URT(2*I-1),URT(2*I)
      WRITE(70,'(1X,3F12.6)')R(I),URT(2*I-1),URT(2*I)
      ENDDO
C     NN(1)=N_R
C     CALL FOURN(URT,NN,1,1)
C     ISS=0
C     DO IS=1,NSTP
C       ISS=ISS+1
C       URRE(ISS)=URT(2*IS-1)*SN_T
C       URIM(ISS)=URT(2*IS)*SN_T
C     ENDDO
      ENDIF
      STOP
      END
C----------------------------------------------------------------------
C  HAMILTONIAN OPERATES ON THE WAVE FUNCTION BY THE FFT-METHOD
C----------------------------------------------------------------------  
      SUBROUTINE XPRO(X0,Y0,AKR,RMST,RINV,SN,V0,
     1PLAN1,PLAN2)
      IMPLICIT REAL*8(A-H,O-Z)
      DOUBLE COMPLEX ARR1,ARR,ART,ARP,ARP1
      INTEGER*8 PLAN1,PLAN2
      PARAMETER (N_R=512)
C
      DIMENSION AKR(N_R)
      DIMENSION V0(N_R)
      DIMENSION X0(N_R),Y0(N_R)
      DIMENSION ARR1(N_R)
      DIMENSION ARR(N_R)
!*******************************************************************************
!
!   This program is distributed with permission
!
!*******************************************************************************
      INTEGER FFTW_R2HC
      PARAMETER (FFTW_R2HC=0)
      INTEGER FFTW_HC2R
      PARAMETER (FFTW_HC2R=1)
      INTEGER FFTW_DHT
      PARAMETER (FFTW_DHT=2)
      INTEGER FFTW_REDFT00
      PARAMETER (FFTW_REDFT00=3)
      INTEGER FFTW_REDFT01
      PARAMETER (FFTW_REDFT01=4)
      INTEGER FFTW_REDFT10
      PARAMETER (FFTW_REDFT10=5)
      INTEGER FFTW_REDFT11
      PARAMETER (FFTW_REDFT11=6)
      INTEGER FFTW_RODFT00
      PARAMETER (FFTW_RODFT00=7)
      INTEGER FFTW_RODFT01
      PARAMETER (FFTW_RODFT01=8)
      INTEGER FFTW_RODFT10
      PARAMETER (FFTW_RODFT10=9)
      INTEGER FFTW_RODFT11
      PARAMETER (FFTW_RODFT11=10)
      INTEGER FFTW_FORWARD
      PARAMETER (FFTW_FORWARD=-1)
      INTEGER FFTW_BACKWARD
      PARAMETER (FFTW_BACKWARD=+1)
      INTEGER FFTW_MEASURE
      PARAMETER (FFTW_MEASURE=0)
      INTEGER FFTW_DESTROY_INPUT
      PARAMETER (FFTW_DESTROY_INPUT=1)
      INTEGER FFTW_UNALIGNED
      PARAMETER (FFTW_UNALIGNED=2)
      INTEGER FFTW_CONSERVE_MEMORY
      PARAMETER (FFTW_CONSERVE_MEMORY=4)
      INTEGER FFTW_EXHAUSTIVE
      PARAMETER (FFTW_EXHAUSTIVE=8)
      INTEGER FFTW_PRESERVE_INPUT
      PARAMETER (FFTW_PRESERVE_INPUT=16)
      INTEGER FFTW_PATIENT
      PARAMETER (FFTW_PATIENT=32)
      INTEGER FFTW_ESTIMATE
      PARAMETER (FFTW_ESTIMATE=64)
      INTEGER FFTW_TIMELIMIT
      PARAMETER (FFTW_TIMELIMIT=1073741824)
      INTEGER FFTW_ESTIMATE_PATIENT
      PARAMETER (FFTW_ESTIMATE_PATIENT=128)
      INTEGER FFTW_BELIEVE_PCOST
      PARAMETER (FFTW_BELIEVE_PCOST=256)
      INTEGER FFTW_NO_DFT_R2HC
      PARAMETER (FFTW_NO_DFT_R2HC=512)
      INTEGER FFTW_NO_NONTHREADED
      PARAMETER (FFTW_NO_NONTHREADED=1024)
      INTEGER FFTW_NO_BUFFERING
      PARAMETER (FFTW_NO_BUFFERING=2048)
      INTEGER FFTW_NO_INDIRECT_OP
      PARAMETER (FFTW_NO_INDIRECT_OP=4096)
      INTEGER FFTW_ALLOW_LARGE_GENERIC
      PARAMETER (FFTW_ALLOW_LARGE_GENERIC=8192)
      INTEGER FFTW_NO_RANK_SPLITS
      PARAMETER (FFTW_NO_RANK_SPLITS=16384)
      INTEGER FFTW_NO_VRANK_SPLITS
      PARAMETER (FFTW_NO_VRANK_SPLITS=32768)
      INTEGER FFTW_NO_VRECURSE
      PARAMETER (FFTW_NO_VRECURSE=65536)
      INTEGER FFTW_NO_SIMD
      PARAMETER (FFTW_NO_SIMD=131072)
      INTEGER FFTW_NO_SLOW
      PARAMETER (FFTW_NO_SLOW=262144)
      INTEGER FFTW_NO_FIXED_RADIX_LARGE_N
      PARAMETER (FFTW_NO_FIXED_RADIX_LARGE_N=524288)
      INTEGER FFTW_ALLOW_PRUNING
      PARAMETER (FFTW_ALLOW_PRUNING=1048576)
CCCCCC
      DO I=1,N_R
         ARR1(I)=DCMPLX(X0(I),Y0(I))
      ENDDO
      CALL DFFTW_EXECUTE_DFT(PLAN1,ARR1,ARR1)
      DO I=1,N_R
         ARR(I)=ARR1(I)*AKR(I)*AKR(I)*SN
      ENDDO
      CALL DFFTW_EXECUTE_DFT(PLAN2,ARR,ARR)
      DO I=1,N_R
         HPSIRE1=0.5D0*RMST*DBLE(ARR(I))*SN
         HPSIRE2=V0(I)*X0(I)
         HPSIIM1=0.5D0*RMST*DIMAG(ARR(I))*SN
         HPSIIM2=V0(I)*Y0(I)
         X0(I)=HPSIRE1+HPSIRE2
         X0(I)=X0(I)*RINV
         Y0(I)=HPSIIM1+HPSIIM2
         Y0(I)=Y0(I)*RINV
      ENDDO
      RETURN
      END
C----------------------------------------------------------------------
C----------------------------------------------------------------------  
      SUBROUTINE LANCZ(X1,Y1,DT,VOLEM,RAV,M,ISTEP,AKR,
     2RMST,RINV,SN_G,V0,PLAN1,PLAN2)
      IMPLICIT REAL*8 (A-H,O-Z)
      PARAMETER (N_R=512)
      PARAMETER (LAD=100)
      DIMENSION X1(N_R),Y1(N_R)
      DIMENSION U0A(N_R),U0B(N_R)
      DIMENSION U1A(N_R),U1B(N_R)
      DIMENSION WA(N_R,LAD),WB(N_R,LAD)
      DIMENSION TT(LAD,2),D(LAD),E(LAD),Z(LAD,LAD),RA(LAD),RB(LAD)
      DIMENSION EE(LAD)
      DIMENSION AKR(N_R)
      DIMENSION V0(N_R)
      INTEGER*8 PLAN1,PLAN2
      HBAR=0.06350781278D0
      SCALEA=DSQRT(VOLEM)
      SCALEI=1.0D0/SCALEA
C
      DO I=1,N_R
         U0A(I)=X1(I)*SCALEA
         U0B(I)=Y1(I)*SCALEA
         U1A(I)=0.0D0
         U1B(I)=0.0D0
      ENDDO
      CALL CHAIN(U0A,U0B,U1A,U1B,
     1WA,WB,TT,M,AKR,RMST,RINV,SN_G,V0,
     3PLAN1,PLAN2)
C     IF (M.EQ.1) RETURN
      IF (M.EQ.1) GO TO 1
      DO I=1,N_R
         X1(I)=0.0D0
         Y1(I)=0.0D0
      ENDDO
      DO I=2,M
         D(I)=TT(I,1)
         E(I)=TT(I-1,2)
      ENDDO
      D(1)=TT(1,1)
C     WRITE(6,1000) (D(I),I=1,M)
C     WRITE(6,1000) (E(I),I=1,M)
      DO I=1,M
         DO J=1,M
            Z(I,J)=0.0D0
            IF (I.EQ.J) Z(I,J)=1.0D0
         ENDDO
      ENDDO
C     DO 1002 I=1,M
C     PRINT 1000,I,D(I),E(I)
C1002  CONTINUE
1000  FORMAT(2X,2I5,2X,F15.5)
      CALL TQLI(D,E,M,Z)
      DO I=1,M
      EE(I)=D(I)*HBAR
      ENDDO
      CALL ODR(M,EE)
      DO I=1,M
      WRITE(9,1000)ISTEP,I,EE(I)
      ENDDO
      WRITE(9,1000)
      DO I=1,M
         SUA=0.0D0
         SUB=0.0D0
         DO J=1,M
            SUA=SUA+Z(I,J)*Z(1,J)*DCOS(D(J)*DT)
            SUB=SUB-Z(I,J)*Z(1,J)*DSIN(D(J)*DT)
         ENDDO
         RA(I)=SUA*SCALEI
         RB(I)=SUB*SCALEI
CCCCCCC  T E S T  CCCCCCCCC
C           SQRVEC=RA(I)*RA(I)+RB(I)*RB(I)
C           PRINT 100,I,RA(I),SQRVEC
C100        FORMAT(' ',I6,2E15.6)
CCCCCCCCCCCCCCCCCCCCCCCCCCC
      ENDDO
CCCCCCC  AVERAGE OF THE FIVE LAST COMPONENTS  CCCCCCC
      RAV=0.0D0
      DO I=M-4,M
         RAV=RAV+RA(I)*RA(I)+RB(I)*RB(I)
      ENDDO
      RAV=RAV*0.2D0
C     WRITE(6,1000) TA,(BR(I),I=1,N)
      DO J=1,M
         DO I=1,N_R
            X1(I)=X1(I)+WA(I,J)*RA(J)-WB(I,J)*RB(J)
            Y1(I)=Y1(I)+WA(I,J)*RB(J)+WB(I,J)*RA(J)
         ENDDO
      ENDDO
C
    1 CONTINUE
      RETURN
      END

C----------------------------------------------------------------------
C----------------------------------------------------------------------  
      SUBROUTINE CHAIN(U0A,U0B,U1A,U1B,
     1WA,WB,T,M,AKR,RMST,RINV,SN_G,V0,
     2PLAN1,PLAN2)
      IMPLICIT REAL*8(A-H,O-Z)
      PARAMETER (N_R=512)
      PARAMETER (LAD=100)
      DIMENSION U0A(N_R),U0B(N_R)
      DIMENSION U1A(N_R),U1B(N_R)
      DIMENSION X0(N_R),Y0(N_R)
      DIMENSION WA(N_R,LAD),WB(N_R,LAD)
      DIMENSION T(LAD,2)
      DIMENSION AKR(N_R)
      DIMENSION V0(N_R)
      INTEGER*8 PLAN1,PLAN2
      BN=0.0D0
      IT=0
   10 IT=IT+1
      DO I=1,N_R
         WA(I,IT)=U0A(I)
         WB(I,IT)=U0B(I)
         X0(I)=U0A(I)
         Y0(I)=U0B(I)
      ENDDO
      CALL XPRO(X0,Y0,
     1AKR,RMST,RINV,SN_G,V0,
     2PLAN1,PLAN2)
C     IF (M.EQ.1) RETURN
      IF (M.EQ.1) GO TO 1
      AN=0.0D0
      DO 3 I=1,N_R
    3 AN=AN+U0A(I)*X0(I)+U0B(I)*Y0(I)
      T(IT,1)=AN
      DO I=1,N_R
         X0(I)=X0(I)-AN*U0A(I)-BN*U1A(I)
         Y0(I)=Y0(I)-AN*U0B(I)-BN*U1B(I)
      ENDDO
      BN=0.0D0
      DO I=1,N_R
         BN=BN+X0(I)*X0(I)+Y0(I)*Y0(I)
      ENDDO
      BN=DSQRT(BN)
      BN1=1.0D0/BN
      DO I=1,N_R
         U1A(I)=U0A(I)
         U1B(I)=U0B(I)
         U0A(I)=X0(I)*BN1
         U0B(I)=Y0(I)*BN1
      ENDDO
      T(IT,2)=BN
      IF (DABS(BN).LT.1.D-6) WRITE(6,289) IT,BN
  289 FORMAT(' BN= ',I4,E10.3)
      IF (IT.LT.M) GO TO 10
    1 CONTINUE
      RETURN
      END
C----------------------------------------------------------------------
C----------------------------------------------------------------------  
      SUBROUTINE TQLI(D,E,N,Z)
      IMPLICIT REAL*8(A-H,O-Z)
      PARAMETER (LAD=100)
      DIMENSION D(LAD),E(LAD),Z(LAD,LAD)
      IF (N.GT.1) THEN
         DO I=2,N
            E(I-1)=E(I)
         ENDDO
         E(N)=0.D0
         DO L=1,N
            ITER=0
 1          DO M=L,N-1
               DD=DABS(D(M))+DABS(D(M+1))
               IF (DABS(E(M))+DD.EQ.DD) GO TO 2
            ENDDO
            M=N
 2          IF (M.NE.L) THEN
               IF (ITER.EQ.30) THEN
                  PRINT *,' TOO MANY ITERATIONS'
                  STOP
               ENDIF
               ITER=ITER+1
               G=(D(L+1)-D(L))/(2.D0*E(L))
               R=DSQRT(G**2+1.D0)
               G=D(M)-D(L)+E(L)/(G+SIGN(R,G))
               S=1.0D0
               C=1.0D0
               P=0.0D0
               DO I=M-1,L,-1
                  F=S*E(I)
                  B=C*E(I)
                  IF (DABS(F).GE.DABS(G)) THEN
                     C=G/F
                     R=DSQRT(C**2+1.D0)
                     E(I+1)=F*R
                     S=1.0D0/R
                     C=C*S
                  ELSE
                     S=F/G
                     R=DSQRT(S**2+1.D0)
                     E(I+1)=G*R
                     C=1.0D0/R
                     S=S*C
                  ENDIF
                  G=D(I+1)-P
                  R=(D(I)-G)*S+2.D0*C*B
                  P=S*R
                  D(I+1)=G+P
                  G=C*R-B
                  DO K=1,N
                     F=Z(K,I+1)
                     Z(K,I+1)=S*Z(K,I)+C*F
                     Z(K,I)=C*Z(K,I)-S*F
                  ENDDO
               ENDDO
               D(L)=D(L)-P
               E(L)=G
               E(M)=0.0D0
               GO TO 1
            ENDIF
         ENDDO
      ENDIF
      RETURN
      END
C----------------------------------------------------------------------
C----------------------------------------------------------------------  
      SUBROUTINE DEFAK(DR,AKR)
*
*     CALCULATION OF FREQUENCIES
*
      IMPLICIT REAL*8 (A-H,O-Z)
      PARAMETER (N_R=512)
      DIMENSION AKR(N_R)
*
      PI=2.0D0*ASIN(1.0D0)
      PI2=PI*2.0D0
      ACONSR=PI2/(N_R*DR)
      NHALFR = N_R/2+1
        DO I=1,NHALFR
          AKR(I)=ACONSR*(I-1)
        ENDDO
        DO I=NHALFR+1,N_R
          AKR(I)=ACONSR*(I-1-N_R)
        ENDDO
        RETURN
        END
C----------------------------------------------------------------------
C  HAMILTONIAN OPERATES ON THE WAVE FUNCTION 
C  BY THE FFT-METHOD TO CALCULATE ENERGY
C----------------------------------------------------------------------  
      SUBROUTINE ENERGY(X1,Y1,AKR,RMST,SN,V0,
     1VAL1,VAL2,VAL,VOLEM,PLAN1,PLAN2)
      IMPLICIT REAL*8(A-H,O-Z)
      COMPLEX*16 ARR1,ARR
      PARAMETER (N_R=512)
      DIMENSION X1(N_R),Y1(N_R)
      DIMENSION AKR(N_R)
      DIMENSION V0(N_R)
      DIMENSION ARR1(N_R),ARR(N_R)
      INTEGER*8 PLAN1,PLAN2
!*******************************************************************************
!
!   This program is distributed with permission
!
!*******************************************************************************
      PARAMETER (FFTW_R2HC=0)
      INTEGER FFTW_HC2R
      PARAMETER (FFTW_HC2R=1)
      INTEGER FFTW_DHT
      PARAMETER (FFTW_DHT=2)
      INTEGER FFTW_REDFT00
      PARAMETER (FFTW_REDFT00=3)
      INTEGER FFTW_REDFT01
      PARAMETER (FFTW_REDFT01=4)
      INTEGER FFTW_REDFT10
      PARAMETER (FFTW_REDFT10=5)
      INTEGER FFTW_REDFT11
      PARAMETER (FFTW_REDFT11=6)
      INTEGER FFTW_RODFT00
      PARAMETER (FFTW_RODFT00=7)
      INTEGER FFTW_RODFT01
      PARAMETER (FFTW_RODFT01=8)
      INTEGER FFTW_RODFT10
      PARAMETER (FFTW_RODFT10=9)
      INTEGER FFTW_RODFT11
      PARAMETER (FFTW_RODFT11=10)
      INTEGER FFTW_FORWARD
      PARAMETER (FFTW_FORWARD=-1)
      INTEGER FFTW_BACKWARD
      PARAMETER (FFTW_BACKWARD=+1)
      INTEGER FFTW_MEASURE
      PARAMETER (FFTW_MEASURE=0)
      INTEGER FFTW_DESTROY_INPUT
      PARAMETER (FFTW_DESTROY_INPUT=1)
      INTEGER FFTW_UNALIGNED
      PARAMETER (FFTW_UNALIGNED=2)
      INTEGER FFTW_CONSERVE_MEMORY
      PARAMETER (FFTW_CONSERVE_MEMORY=4)
      INTEGER FFTW_EXHAUSTIVE
      PARAMETER (FFTW_EXHAUSTIVE=8)
      INTEGER FFTW_PRESERVE_INPUT
      PARAMETER (FFTW_PRESERVE_INPUT=16)
      INTEGER FFTW_PATIENT
      PARAMETER (FFTW_PATIENT=32)
      INTEGER FFTW_ESTIMATE
      PARAMETER (FFTW_ESTIMATE=64)
      INTEGER FFTW_TIMELIMIT
      PARAMETER (FFTW_TIMELIMIT=1073741824)
      INTEGER FFTW_ESTIMATE_PATIENT
      PARAMETER (FFTW_ESTIMATE_PATIENT=128)
      INTEGER FFTW_BELIEVE_PCOST
      PARAMETER (FFTW_BELIEVE_PCOST=256)
      INTEGER FFTW_NO_DFT_R2HC
      PARAMETER (FFTW_NO_DFT_R2HC=512)
      INTEGER FFTW_NO_NONTHREADED
      PARAMETER (FFTW_NO_NONTHREADED=1024)
      INTEGER FFTW_NO_BUFFERING
      PARAMETER (FFTW_NO_BUFFERING=2048)
      INTEGER FFTW_NO_INDIRECT_OP
      PARAMETER (FFTW_NO_INDIRECT_OP=4096)
      INTEGER FFTW_ALLOW_LARGE_GENERIC
      PARAMETER (FFTW_ALLOW_LARGE_GENERIC=8192)
      INTEGER FFTW_NO_RANK_SPLITS
      PARAMETER (FFTW_NO_RANK_SPLITS=16384)
      INTEGER FFTW_NO_VRANK_SPLITS
      PARAMETER (FFTW_NO_VRANK_SPLITS=32768)
      INTEGER FFTW_NO_VRECURSE
      PARAMETER (FFTW_NO_VRECURSE=65536)
      INTEGER FFTW_NO_SIMD
      PARAMETER (FFTW_NO_SIMD=131072)
      INTEGER FFTW_NO_SLOW
      PARAMETER (FFTW_NO_SLOW=262144)
      INTEGER FFTW_NO_FIXED_RADIX_LARGE_N
      PARAMETER (FFTW_NO_FIXED_RADIX_LARGE_N=524288)
      INTEGER FFTW_ALLOW_PRUNING
      PARAMETER (FFTW_ALLOW_PRUNING=1048576)
CCCCCC
      DO I=1,N_R
         ARR1(I)=DCMPLX(X1(I),Y1(I))
      ENDDO
      CALL DFFTW_EXECUTE_DFT(PLAN1,ARR1,ARR1)
      DO I=1,N_R
         ARR(I)=ARR1(I)*AKR(I)*AKR(I)*SN
      WRITE(102,'(1X,4F12.6)')ARR1(I),AKR(I),SN
      ENDDO
      CALL DFFTW_EXECUTE_DFT(PLAN2,ARR,ARR)
      VAL1=0.0D0
      VAL2=0.0D0
      DO I=1,N_R
         HPSIRE1=0.5D0*RMST*DBLE(ARR(I))*SN
         HPSIRE2=V0(I)*X1(I)
CCC
         HPSIIM1=0.5D0*RMST*DIMAG(ARR(I))*SN
         HPSIIM2=V0(I)*Y1(I)
         VAL1=VAL1+HPSIRE1*X1(I)+HPSIIM1*Y1(I)
         VAL2=VAL2+HPSIRE2*X1(I)+HPSIIM2*Y1(I)
      ENDDO
      VAL=VAL1+VAL2
      WRITE(101,*)VAL1,VAL2,VAL
      RETURN
      END
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     Eckart potential         C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE POTF(R,EN)
      IMPLICIT REAL*8 (A-H,O-Z)
      A1=1.0D0
      A2=2.0D0
      EN=A1/DCOSH(A2*R)/DCOSH(A2*R)
      RETURN
      END
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     NORMALIZATION CHECK OF THE TRANSLATIONAL WAVEFUNCTION (GWP)   C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE TRANSF(PSIRE,PSIIM)
      IMPLICIT REAL*8(A-H,O-Z)
      COMPLEX*16 ZI,A1,XI,SS
      PARAMETER (N_R=512)
      DIMENSION PSIRE(N_R),PSIIM(N_R)
      EKIN=1.0D0
      EMU=1.0D0
      ZI=DCMPLX(0.0D0,1.0D0)
      PI=4.0D0*DATAN(1.0D0)
      RMIN=-50.0D0
      RMAX=50.0D0
      DR=(RMAX-RMIN)/DFLOAT(N_R)
      HBAR=0.06350781278D0
      AK_0=SQRT(2.0D0*EMU*EKIN)/HBAR
      R2_0=3.5D0
      R2_F=1.68D0
      SIGMA=0.21D0
      QQ=2.0D0*(R2_0-R2_F)/AK_0
      A1=1.0D0/(4.0D0*SIGMA*SIGMA-ZI*QQ)
      A2=8.0D0*SIGMA*SIGMA/(16.0D0*SIGMA**4+QQ*QQ)
      AN=(A2/PI)**0.25
      SS=DCMPLX(0.0D0,0.0D0)
      DO I=1,N_R
      R2=RMIN+(I-1)*DR
      XI=AN*EXP(-ZI*AK_0*R2-A1*(R2-R2_0)**2)
      PSIRE(I)=DBLE(XI)
      PSIIM(I)=DIMAG(XI)
      SS=SS+CONJG(XI)*XI*DR
      WRITE(11,'(1X,4F12.6)')R2,DBLE(XI),DIMAG(XI),ABS(XI)
      ENDDO
      WRITE(6,'(1X,2F12.6)')DBLE(SS),DIMAG(SS)
      RETURN
      END                             
CCCCCC
      SUBROUTINE TRANSF1(PSIRE,PSIIM)
      IMPLICIT REAL*8(A-H,O-Z)
      COMPLEX*16 ZI,XI,SS
      PARAMETER (N_R=512)
      DIMENSION PSIRE(N_R),PSIIM(N_R)
      ZI=DCMPLX(0.0D0,1.0D0)
      PI=4.0D0*DATAN(1.0D0)
      HBAR=0.06350781278D0
      AM=1.0D0
      AK0=20.0D0
      RMIN=-50.0D0
      RMAX=50.0D0
      DR=(RMAX-RMIN)/DFLOAT(N_R)
      R0=-3.0D0
      DELTAR=0.2D0
      AN=1.0D0/(2.0D0*PI*DELTAR*DELTAR)
      AN=AN**0.25D0
      SS=DCMPLX(0.0D0,0.0D0)
      DO I=1,N_R
      R2=RMIN+(I-1)*DR
      QQ=(R2-R0)*(R2-R0)/4.0D0/DELTAR/DELTAR
      XI=AN*EXP(-ZI*AK0*R2-QQ)
      PSIRE(I)=DBLE(XI)
      PSIIM(I)=DIMAG(XI)
      SS=SS+CONJG(XI)*XI*DR
      WRITE(11,'(1X,4F12.6)')R2,DBLE(XI),DIMAG(XI),ABS(XI)
      ENDDO
      WRITE(6,'(1X,2F12.6)')DBLE(SS),DIMAG(SS)
      RETURN
      END
CCCCCC
      SUBROUTINE ODR(N,A)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION A(N)
      DO  40  L=1,N
      ATEST=1.0E+12
      DO 41 J=L,N
      IF(A(J)-ATEST)42,41,41
   42 ATEST=A(J)
      JTEST=J
   41 CONTINUE
      A(JTEST)=A(L)
      A(L)=ATEST
   40 CONTINUE
      RETURN
      END
C----------------------------------------------------------------------
      SUBROUTINE INITIAL_WEIGHT(DDT,EKIN,IDX,AM,AT,ET,CKI)
      IMPLICIT REAL*8 (A-H,O-Z)
      PARAMETER (NSTP=2048)
      PARAMETER (NE=92)
      DIMENSION AT(NSTP)
      DIMENSION CKI(NE),ET(NE)
      DIMENSION AKI(NE)
CCCC
      PI=4.0D0*DATAN(1.0D0)
      DELTAR=0.2D0
      HBAR=0.06350781278D0
      EK=EKIN
CC
      AK_0=SQRT(2.0D0*AM*EK)/HBAR
      WRITE(6,*)
      WRITE(6,*)'AK_0',AK_0
      WRITE(6,*)
C
      WRITE(6,*)
      WRITE(6,*)'WEIGHT FACTOR FOR INCOMING WAVE FUNCTION'
      WRITE(6,*)
      CALL DEFAT(DDT,AT)
      IE=0
      DO I=IDX,NE+IDX-1
      IE=IE+1
      ET(IE)=HBAR*AT(I)
      AKI(IE)=SQRT(2.0D0*AM*ET(IE))/HBAR
      CKI(IE)=SQRT(2.0D0/PI)*DELTAR
     1       *EXP(-2.0D0*DELTAR*DELTAR*(AKI(IE)-AK_0)**2)
      WRITE(6,44)IE,ET(IE),AKI(IE),CKI(IE)
      ENDDO
  44  FORMAT(1X,I4,4X,3F16.6)
      RETURN
      END
CCCCCC
      SUBROUTINE DEFAT(DT,AT)
*
*     CALCULATION OF FREQUENCIES
*
      IMPLICIT REAL*8 (A-H,O-Z)
      PARAMETER (NSTP=2048)
      DIMENSION AT(NSTP)
*
      PI=2.0D0*ASIN(1.0D0)
      PI2=PI*2.0D0
      ACONST=PI2/(NSTP*DT)
      NHALFT = NSTP/2+1
        DO I=1,NHALFT
          AT(I)=ACONST*(I-1)
        ENDDO
        DO I=NHALFT+1,NSTP
          AT(I)=ACONST*(I-1-NSTP)
        ENDDO
      RETURN
      END
CCCCCC
      SUBROUTINE FOURN(DATA,NN,NDIM,ISIGN)
      INTEGER ISIGN,NDIM,NN(NDIM)
C      REAL DATA(*)
      DOUBLE PRECISION DATA(*)
      INTEGER I1,I2,I2REV,I3,I3REV,IBIT,IDIM,IFP1,IFP2,IP1,IP2,IP3,K1,
     *K2,N,NPREV,NREM,NTOT
C      REAL TEMPI,TEMPR
      DOUBLE PRECISION TEMPI,TEMPR
      DOUBLE PRECISION THETA,WI,WPI,WPR,WR,WTEMP
      NTOT=1
      DO IDIM=1,NDIM
         NTOT=NTOT*NN(IDIM)
      ENDDO
      NPREV=1
      DO IDIM=1,NDIM
         N=NN(IDIM)
         NREM=NTOT/(N*NPREV)
         IP1=2*NPREV
         IP2=IP1*N
         IP3=IP2*NREM
         I2REV=1
         DO I2=1,IP2,IP1
            IF (I2.LT.I2REV) THEN
               DO I1=I2,I2+IP1-2,2
                  DO I3=I1,IP3,IP2
                     I3REV=I2REV+I3-I2
                     TEMPR=DATA(I3)
                     TEMPI=DATA(I3+1)
                     DATA(I3)=DATA(I3REV)
                     DATA(I3+1)=DATA(I3REV+1)
                     DATA(I3REV)=TEMPR
                     DATA(I3REV+1)=TEMPI
                  ENDDO
               ENDDO
            ENDIF
            IBIT=IP2/2
   1        IF ((IBIT.GE.IP1).AND.(I2REV.GT.IBIT)) THEN
               I2REV=I2REV-IBIT
               IBIT=IBIT/2
               GOTO 1
            ENDIF
            I2REV=I2REV+IBIT
         ENDDO
         IFP1=IP1
   2     IF (IFP1.LT.IP2) THEN
            IFP2=2*IFP1
            THETA=ISIGN*6.28318530717959D0/(IFP2/IP1)
            WPR=-2.0D0*SIN(0.5D0*THETA)**2
            WPI=SIN(THETA)
            WR=1.0D0
            WI=0.0D0
            DO I3=1,IFP1,IP1
               DO I1=I3,I3+IP1-2,2
                  DO I2=I1,IP3,IFP2
                     K1=I2
                     K2=K1+IFP1
                     TEMPR=SNGL(WR)*DATA(K2)-SNGL(WI)*DATA(K2+1)
                     TEMPI=SNGL(WR)*DATA(K2+1)+SNGL(WI)*DATA(K2)
                     DATA(K2)=DATA(K1)-TEMPR
                     DATA(K2+1)=DATA(K1+1)-TEMPI
                     DATA(K1)=DATA(K1)+TEMPR
                     DATA(K1+1)=DATA(K1+1)+TEMPI
                  ENDDO
               ENDDO
               WTEMP=WR
               WR=WR*WPR-WI*WPI+WR
               WI=WI*WPR+WTEMP*WPI+WI
            ENDDO
            IFP1=IFP2
            GOTO 2
         ENDIF
         NPREV=N*NPREV
      ENDDO
      RETURN
      END
